#Email Config
mail:
  host: smtp.gmail.com
  port: 587
  username: juniorjavajoboffers@gmail.com
  password: pfhdvtnmwkwzizgv
  default-encoding: UTF-8
  properties:
    mail:
      mime:
        charset: UTF
      smtp:
        writetimeout: 10000
        connectiontimeout: 10000
        timeout: 10000
        auth: true
        starttls:
          enable: true
          required: true
  verify:
    host: htttp://localhost:8080

