spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/junior-offers
    username: root
    password: tomek
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  #email config
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
    verify:
      host: http://localhost:8080
    protocol: smtp
#http
offer:
  sendEmailOcurrence: "0 00 18 * * *"
  fetchOffersOcurrence: "0 58 17 * * *"
  http:
    client:
      config:
        connectionTimeout: 1000
        readTimeout: 1000
        uri: https://nofluffjobs.com/api/search/posting?page=1&salaryCurrency=PLN&salaryPeriod=month&region=pl

